### ISSUE TITLE
VS Code "Type annotations can only be used in TypeScript files"

### ISSUE THREAD

**Issue by mvolkmann** [halfnelson/svelte-type-checker#4]
Do you use VS Code? If so, have you found a way to stop it from complaining about type annotations in `.svelte` files?

I thought what I needed to do was the following, but this didn't work.

1) `npm install -D svelte-preprocess`

2) Create a `svelte.config.js` file at the root of the project containing this:

```js
const sveltePreprocess = require('svelte-preprocess');

module.exports = {
  preprocess: sveltePreprocess()
};
```

3)  Configure it in `rollup.config.js` like this:

```js
...
import sveltePreprocess from 'svelte-preprocess';
...
export default {
...
  plugins: [
    svelte({
      ...
      preprocess: sveltePreprocess()
    }),
    ...
  ],
  ...
};
...
```

4) Restart VS Code

But after all this VS Code still complains about type annotations in `.svelte` files.

**Comment by mvolkmann** [comment]
Maybe the answer is that I need to use the VS Code "Svelte Type Checker" extension. I tried that, but I still get the same errors on all my type annotations. See https://github.com/halfnelson/svelte-type-checker-vscode/issues/5.

**Comment by halfnelson** [comment]
Does this still happen?

**Comment by mvolkmann** [comment]
Yes. I just walked through all the steps again with a new Svelte project. VS Code puts a red squiggly below every type annotation. Hovering over them gives a popup that says "Type annotations can only be used in TypeScript files."

**Comment by halfnelson** [comment]
When you hover over it, as well as the error it should say which plugin was
the source of the error on the right side of the hover window. What does it
say for you?

**Comment by mvolkmann** [comment]
I don't see a plugin name. A screenshot is attached.
<img width="900" alt="Screen Shot 2020-05-04 at 6 54 18 PM" src="https://user-images.githubusercontent.com/79312/81024365-d28d2680-8e38-11ea-859e-36d0a9486de3.png">

I'm all in for helping resolve this, so let me know if there is anything else you want to me to try.

**Comment by halfnelson** [comment]
If it were coming from type checker it would say svelte-type-checker to the
right. The svelte plugin puts a "ts" to the right. So my guess is that
another plugin is doing this. Does the language in the status bar say
Svelte or Html? You can try disabling all extensions except for svelte beta
and type checker. Then enable them one by one until the error comes back

**Comment by mvolkmann** [comment]
When viewing a `.svelte` file the language in the status bar is "HTML". I disabled all extensions except Svelte Beta and Svelte Type Checker. Then I reloaded the window. Nothing changed. I still get "Type annotations can only be used in TypeScript files."

**Comment by halfnelson** [comment]
I think your problem is that the language is detected as html. It needs to
be detected as svelte. This is probably due to a file extension mapping  in
vscode that points .svelte files to HTML. You would have added this
extension mapping in the past

**Comment by mvolkmann** [comment]
You are correct that if I remove this, the warnings about type annotations  go away.

```json
  "files.associations": {
    "*.svelte": "html"
  }
```

But then I get new problems like the inability to run Prettier on `.svelte` files on save. But this isn't your issue. It seems I have to pick my poison and I'd rather have format on save working. The perfect VS Code setup for Svelte still eludes me.

**Comment by halfnelson** [comment]
I thought the svelte plugin has a formatter
 Not sure when it runs

**Comment by mvolkmann** [comment]
The svelte plugin has never worked for me and it hasn't been updated since October 7, 2019. That's why I went with suggestions to mark .svelte files as HTML.

**Comment by rondonjon** [comment]
> I don't see a plugin name. A screenshot is attached.
> <img alt="Screen Shot 2020-05-04 at 6 54 18 PM" width="900" src="https://user-images.githubusercontent.com/79312/81024365-d28d2680-8e38-11ea-859e-36d0a9486de3.png">
> 
> I'm all in for helping resolve this, so let me know if there is anything else you want to me to try.

Have you tried adding `language="typescript"` to your `<script>` tag?
